oauth2:
  kakao:
    client-id: f9580fd7455b0683b9b55e0d431b1e00
    client-secret: G6hy1S3Z1xsnBiavVyXCYyRxdWa9kzh4
    redirect-uri : "{baseUrl}/login/oauth2/code/kakao"

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1091319332721-plbgp2gj700nqd4609j3a7m8sr8oau33.apps.googleusercontent.com
            client-secret: hbaf-BI4VgLekSA28TjQwNuf
            scope: profile, email

          naver:
            client-id: Yyh9UQTYx3vrrHwEEI_Y
            client-secret: pqZMgpGEc6
            redirect-uri : "{baseUrl}/login/oauth2/code/naver"
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

    profiles:
      include: oauth
#  mustache:

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mustache:
    cache: false
#    suffix: .html

